version: '3.8'

services:
  orchestrator:
    build: .
    container_name: sentiment-orchestrator
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - API_PORT=8000
      - DEBUG=false
      - LOG_LEVEL=INFO
      - DEFAULT_TIMEOUT_MINUTES=15
      - CSV_PROCESSOR_URL=http://model-a:8001/process-csv
      - JSON_PROCESSOR_URL=http://model-b:8002/process-context
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - sentiment-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching and task queuing (for advanced setups)
  redis:
    image: redis:7-alpine
    container_name: sentiment-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - sentiment-network
    command: redis-server --appendonly yes

  # Optional: PostgreSQL for job tracking and results storage
  postgres:
    image: postgres:15-alpine
    container_name: sentiment-postgres
    environment:
      POSTGRES_DB: sentiment_analysis
      POSTGRES_USER: sentiment_user
      POSTGRES_PASSWORD: sentiment_password_2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - sentiment-network

  # Example Model A (CSV Processor) - Replace with your actual service
  model-a:
    image: nginx:alpine
    container_name: csv-processor-mock
    ports:
      - "8001:80"
    volumes:
      - ./mock-services/model-a.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sentiment-network
    restart: unless-stopped

  # Example Model B (JSON Processor) - Replace with your actual service
  model-b:
    image: nginx:alpine
    container_name: json-processor-mock
    ports:
      - "8002:80"
    volumes:
      - ./mock-services/model-b.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sentiment-network
    restart: unless-stopped

networks:
  sentiment-network:
    driver: bridge

volumes:
  redis_data:
  postgres_data: